### ISSUE TITLE
Fetching a list of IMAP folders not working on Android

### ISSUE THREAD

**Issue by toastyyy** [aleksandar888/cordova-plugin-imap#1]
Hi,

I tried to get a list of IMAP folders using this plugin, but the list is always empty. However, fetching a list of messages is working, so this is not a general problem with my setup.

I found that you are using a pattern to fetch a list of folders [here](https://github.com/aleksandar888/cordova-plugin-imap/blob/3b3da80293c37b3f41da9dc2035a5a4677fae2f6/src/android/Imap.java#L412). On my device, `pattern` contained a stringified "null", so in fact was calling `store.getDefaultFolder().list("null");` which results in an empty list for my test mail account.

I created a workaround for me that checks for this null value and if so, use "*" instead to search for all folders:

`Folder[] folders = store.getDefaultFolder().list((pattern == null || pattern.equals("null")) ? "*" : pattern);`

This will obviously fail if anyone really wants to search for "null". I am not a java dev, so I am unsure how to really fix this. Any suggestions?

I am using a real device running Android 10 and use this package inside of an Ionic Capacitor App.

package.json:

```
{
  "dependencies": {
    "@angular/common": "^9.1.13",
    "@angular/core": "^9.1.13",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "^9.1.13",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "^9.1.13",
    "@angular/platform-browser-dynamic": "^9.1.13",
    "@angular/router": "^9.1.13",
    "@capacitor/android": "3.2.5",
    "@capacitor/app": "1.0.5",
    "@capacitor/core": "3.2.5",
    "@capacitor/device": "^1.0.5",
    "@capacitor/haptics": "1.1.2",
    "@capacitor/keyboard": "1.1.2",
    "@capacitor/push-notifications": "^1.0.6",
    "@capacitor/status-bar": "1.0.5",
    "@ionic-native/base64": "^5.36.0",
    "@ionic-native/contacts": "^5.36.0",
    "@ionic-native/core": "^5.36.0",
    "@ionic-native/device": "^5.36.0",
    "@ionic-native/image-picker": "^5.36.0",
    "@ionic-native/imap": "^5.36.0",
    "@ionic-native/splash-screen": "^5.36.0",
    "@ionic-native/status-bar": "^5.36.0",
    "@ionic/angular": "^5.8.5",
    "@ionic/storage": "^3.0.6",
    "@ionic/storage-angular": "^3.0.6",
    "angularfire2": "^5.2.3",
    "capacitor-firebase-auth": "^3.0.0",
    "com-badrit-base64": "^0.2.0",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-imap": "^1.1.0",
    "cordova-plugin-telerik-imagepicker": "^2.3.6",
    "core-js": "^2.5.4",
    "crypto-js": "^4.1.1",
    "firebase": "^7.5.0",
    "jetifier": "^2.0.0",
    "rxjs": "^6.3.3",
    "uuid": "^8.3.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.901.15",
    "@angular-devkit/build-angular": "^0.901.15",
    "@angular-devkit/core": "^9.1.15",
    "@angular-devkit/schematics": "^9.1.15",
    "@angular/cli": "^9.1.15",
    "@angular/compiler": "^9.1.13",
    "@angular/compiler-cli": "^9.1.13",
    "@angular/language-service": "^9.1.13",
    "@capacitor/cli": "3.2.5",
    "@ionic/angular-toolkit": "^3.1.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.13.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.8.2"
  },
}
```

**Comment by aleksandar888** [comment]
Thank you for reporting the issue. 

I'll try to reproduce the error and improve the feature for listing folders.

**Comment by toastyyy** [comment]
Hey Aleksandar,

thanks for looking into it. I think it is not a problem with your package though. The wrapper from the `@ionic-native/imap` package I have installed is missing the `pattern` parameter for the method `listMailFolders`. This has been added in version `5.37.0` inside of  `@awesome-cordova-plugins/imap` (which seems to be the same package?!). However for `@ionic-native/imap` the latest version is `5.36.0` and if you follow the instructions [here](https://ionicframework.com/docs/native/imap) you probably will investigate the same issue as me.

**Comment by aleksandar888** [comment]
The plugin's wrapper that you can install by running _npm install @ionic-native/imap_ is not the latest version of the wrapper.

When I updated the package (plugin) from version 1.0.0 to 1.1.0 I have updated the plugin's wrapper. 
The newest plugin wrapper is available on this link: https://github.com/danielsogl/awesome-cordova-plugins/blob/master/src/%40awesome-cordova-plugins/plugins/imap/index.ts 

It includes the newest features of the package which are not available with the old wrapper.
I suggest you try to copy the code of the wrapper within your : _**node_modules/@ionic-native/imap/index.d.ts**_ and **_node_modules/@ionic-native/imap/ngx/index.d.ts_**
If you are using Capacitor, you might have different folder path. My point is to basically update the plugin's wrapper manually.

I have contacted the Ionic's support team and asked them why the plugin is not updated on the Ionic's official documentation. They replied to me, that the Ionic Site is outdated since over a year and they will also remove the site in the near future. They will release a new documentation in near future.
If you're curious you can read more here: https://ionicframework.com/blog/a-new-chapter-for-ionic-native/


Until now, I can't see much of their new documentation. 

By the way, Mr. Daniel Sogl told me that the plugin's documentation should be available on this link: https://danielsogl.gitbook.io/awesome-cordova-plugins/plugins/imap
But sadly, this link is empty.

Tell me if this description was helpful.

Regards,
Aleksandar

**Comment by toastyyy** [comment]
Thank you for the detailed answer!
I managed to use the new wrapper. The following command did the trick for me:

```
npm install @awesome-cordova-plugins/core --legacy-peer-deps
npm install @awesome-cordova-plugins/imap --legacy-peer-deps
```

I think we can consider this issue closed?
