### ISSUE TITLE
Ouath?

### ISSUE THREAD

**Issue by joecocode** [aleksandar888/cordova-plugin-imap#2]
Hi,
Thank you for making this!
Is there a way to connect to imap servers that use oauth (Gmail, yahoo, AOL, etc.)?

**Comment by aleksandar888** [comment]
Hi,

I'm not sure if there's a way to connect to these email providers using Imap and Oauth authentication.
Maybe you can look for a way to authenticate with Oauth on JavaMail https://javaee.github.io/javamail/OAuth2 (for Android) and MailCore http://libmailcore.com/ (for iOS). If you find such an option, you can extend the implementation of the plugin on your project. I'm not sure if there's such an option.

From my experience, in order to interact with Gmail, you can use Gmail API. You can find more info about the API here: https://developers.google.com/gmail/api/reference/rest/v1/users.messages 

To authenticate so you can use Gmail API you need to create a project here: https://console.cloud.google.com/ 
All the required credentials can be obtained from here.
You can use this documentation to setup the authentication: https://developers.google.com/identity/protocols/oauth2/web-server#httprest 


Yahoo, just like Gmail has an API service, but in order to utilize it you must get approval. You can read this documentation: https://developer.yahoo.com/api/ . Otherwise, the authentication process and API interaction is similar like Gmail's.

Sadly, I've never worked with AOL, so I can't share any experience. 

I apologize for the late response.
